### ISSUE TITLE
Can you run a build for 1.3.2?

### ISSUE THREAD

**Issue by elico** [naa0yama/vyos-build-lts#5]
VyOS was upgrade to 1.3.2, it would be very helpful if you could build the 1.3.2 and publish the iso.

Thanks,
Eliezer

**Comment by naa0yama** [comment]
Hi, elico

https://github.com/naa0yama/vyos-build-lts/releases/tag/1.3.2

**Comment by elico** [comment]
@naa0yama Thanks!!!
