### ISSUE TITLE
可否继续提供编译好的LTS_ISO下载？

### ISSUE THREAD

**Issue by librecats** [naa0yama/vyos-build-lts#9]
RT，感谢您的分享，期待能继续提供。

**Comment by si458** [comment]
plz refer to https://github.com/naa0yama/vyos-build-lts/issues/8
they was forced to stop automated builds of the LTS due to licencing
so you have to fork repo and run it yourself then delete isos afterwards

**Comment by naa0yama** [comment]
As you commented.

isos is no longer publicly available as we have received and addressed licensing issues from the VyOS maintainers.

However, they said I could keep it as a sample for GitHub Actions, so I am releasing it.

You can clone it and use it in your private repositories.
